# Generated by Django 6.0 on 2025-12-31 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10)),
                ('lap_model', models.CharField(max_length=10)),
                ('cpu_kinds', models.CharField(choices=[('Intel Core i3', 'Intel Core i3'), ('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i7'), ('Intel Core i9', 'Intel Core i9'), ('AMD Ryzen 3', 'AMD Ryzen 3'), ('AMD Ryzen 5', 'AMD Ryzen 5'), ('AMD Ryzen 7', 'AMD Ryzen 7'), ('AMD Ryzen 9', 'AMD Ryzen 9'), ('AMD A4', 'AMD A4'), ('AMD A6', 'AMD A6'), ('AMD A8', 'AMD A8'), ('AMD A10', 'AMD A10')], max_length=100)),
                ('cpu_detail', models.CharField(max_length=10)),
                ('ram', models.IntegerField()),
                ('storage', models.CharField(choices=[('250 GB', ''), ('500 GB', '500 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('4 TB', '4 TB')], max_length=50)),
                ('storage_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=50)),
                ('gpu', models.CharField(choices=[('integrated', 'integrated'), ('dedicated ', 'dedicated ')], max_length=10)),
                ('gpu_detail', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='trzp.laptop')),
            ],
        ),
    ]
