# Generated by Django 6.0 on 2025-12-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='lap_model',
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(choices=[('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Dell', 'Dell'), ('Surface', 'Surface')], max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu_detail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(choices=[('250 GB', '250 GB'), ('500 GB', '500 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('4 TB', '4 TB')], max_length=50),
        ),
    ]
