# Generated by Django 6.0 on 2025-12-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0002_remove_laptop_lap_model_laptop_laptop_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_model',
            field=models.CharField(max_length=30),
        ),
    ]
