# Generated by Django 6.0 on 2025-12-31 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0003_alter_laptop_laptop_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='text',
        ),
    ]
