# Generated by Django 6.0 on 2025-12-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0004_remove_price_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
