# Generated by Django 6.0 on 2025-12-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0005_laptop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(null=True, upload_to='lap_imgs'),
        ),
    ]
