# Generated by Django 6.0 on 2026-01-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0007_alter_laptop_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='gpu',
            field=models.CharField(choices=[('integrated', 'Integrated'), ('dedicated ', 'Dedicated ')]),
        ),
    ]
