# Generated by Django 6.0 on 2026-01-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0009_alter_laptop_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=40)),
                ('power', models.CharField(max_length=40)),
                ('gpu', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='laptop',
            name='type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(choices=[('250 GB', '250 GB'), ('256 GB', '256 GB'), ('500 GB', '500 GB'), ('512 GB', '512 GB'), ('650 GB', '650 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('4 TB', '4 TB'), ('8 TB', '8 TB')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
