# Generated by Django 6.0 on 2026-01-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0010_computer_laptop_description_laptop_price_laptop_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
