# Generated by Django 6.0 on 2026-01-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0011_alter_laptop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='case',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
