# Generated by Django 6.0 on 2026-01-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0012_computer_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
