# Generated by Django 6.0 on 2026-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0013_alter_laptop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.CharField(choices=[('PlayStation', 'PlayStation'), ('Xbox', 'Xbox')], max_length=15)),
                ('type', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
