# Generated by Django 6.0 on 2026-01-01 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0014_gameconsole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('image', models.ImageField(null=True, upload_to='prod_imgs')),
                ('product_summery', models.CharField(max_length=30)),
                ('product_is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(null=True, upload_to='comp_imgs'),
        ),
        migrations.AddField(
            model_name='gameconsole',
            name='image',
            field=models.ImageField(null=True, upload_to='consols_imgs'),
        ),
        migrations.CreateModel(
            name='ProductsListView',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trzp.products')),
            ],
            bases=('trzp.products',),
        ),
        migrations.AddField(
            model_name='computer',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='p_computers', to='trzp.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameconsole',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='p_gameconsoles', to='trzp.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='p_laptops', to='trzp.products'),
            preserve_default=False,
        ),
    ]
