# Generated by Django 6.0 on 2026-01-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0015_products_computer_image_gameconsole_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductsListView',
        ),
    ]
