# Generated by Django 6.0 on 2026-01-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trzp', '0016_products_slug_delete_productslistview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
